# Generated by Django 3.2.11 on 2022-01-16 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productcategory', '0002_auto_20220116_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='category_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Productcategory_category_name', to='productcategory.category'),
            preserve_default=False,
        ),
    ]
